package hashTable;

/**
 * ＜ａ　href="https://leetcode.com/problems/find-the-difference/">原文链接</a>
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 */

import java.util.HashMap;

/**
 * 题目的意思是现在有两个字符串，字符串t是由字符串s经过随机打乱并且添加了一个字符后得到的，那么问这个添加了的字符是哪个？
 */
public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        HashMap<Character, Integer> map = new HashMap<>();

        for (int i = 0; i < s.length(); i++) {
            char curr = s.charAt(i);

            if (map.containsKey(curr)) {
                map.put(curr, map.get(curr) + 1);
            } else {
                map.put(curr, 1);
            }
        }

        for (int i = 0; i < t.length(); i++) {
            char curr = t.charAt(i);

            if (map.containsKey(curr)) {
                int number = map.get(curr);

                if (number == 1) {
                    map.remove(curr);
                } else {
                    map.put(curr, number - 1);
                }
            } else {
                return curr;
            }
        }
        return '-';
    }
}
